version: "3.1"

services:
  neo4j:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_AUTH=neo4j/test
      - apoc.export.file.enabled=true
      - apoc.import.file.enabled=true
      - apoc.user.log.type=raw
      - apoc.user.log.window.ops=10000
      - apoc.trigger.enabled=true
