FROM neo4j:5.1.0-community

RUN wget https://github.com/neo4j/apoc/releases/download/5.2.1/apoc-5.2.1-core.jar -P /var/lib/neo4j/plugins/

RUN wget https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/5.2.0/apoc-5.2.0-extended.jar -P /var/lib/neo4j/plugins/

RUN wget https://github.com/neo4j/graph-data-science/releases/download/2.2.3/neo4j-graph-data-science-2.2.3.jar -P /var/lib/neo4j/plugins/